FROM python:3.9

RUN pip3 install flask
RUN pip3 install -U flask-cors
RUN pip3 install psycopg2-binary
RUN pip3 install elasticsearch
RUN pip3 install pandas
RUN pip3 install names
RUN pip3 install scikit-learn
